CREATE TABLE doctors (
    id SERIAL PRIMARY KEY,
    person_id INT NOT NULL UNIQUE,
    crm VARCHAR(14) UNIQUE NOT NULL,
    specialty VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE
);